Added Draw the Triangle questions under Advanced SELECT. Provided alternate solution for Weather Observation Station 10. Reverted the changes suggested in previous Pull request.
Thomas-George-T/HackerRank-SQL-Challenges-Solutions pull request #19
Opened 2022-08-03 12:50 UTC by StackDSA

2022-08-03 16:35 UTC, Thomas-George-T requested changes
Hi @StackDSA, Thank you for making the changes from before.

Could you please delete the unchanged files and pull it again using git. This way it will not show a change in the PR. 

Please commit it to the same branch and it will show up in the PR request here. It's not necessary to close this and raise a new PR this way.

Thanks!

2022-08-03 16:35 UTC, Thomas-George-T commented on Advanced Select/Type of Triangle.sql
> +
Could you please delete this file and pull it again since there's no change in the file. This way it will not show a change in the PR. Thanks!

2022-08-03 16:35 UTC, Thomas-George-T commented on Basic Join/Average Population of Each Continent.sql
> +select country.continent, floor(avg(city.population)) from country join city on city.countrycode = country.code group by country.continent;
Could you please delete this file and pull it again since there's no change in the file. This way it will not show a change in the PR. Thanks!

2022-08-03 16:35 UTC, Thomas-George-T commented on Basic Select/Weather-Observation-Station-5.sql
> +select distinct(City),length(city) from station order by length(city) desc, city asc limit 1;
Could you please delete this file and pull it again since there's no change in the file. This way it will not show a change in the PR. Thanks!

2022-08-03 16:35 UTC, Thomas-George-T commented on Basic Select/Weather-Observation-Station-8.sql
> +
Could you please delete this file and pull it again since there's no change in the file. This way it will not show a change in the PR. Thanks!

2022-08-08 10:45 UTC, StackDSA commented
> Hi @StackDSA, Thank you for making the changes from before.
> 
> Could you please delete the unchanged files and pull it again using git. This way it will not show a change in the PR.
> 
> Please commit it to the same branch and it will show up in the PR request here. It's not necessary to close this and raise a new PR this way.
> 
> Thanks!

Hey! I have deleted the files you suggested. I didn't quite get the meaning of 'pull it again'. Let me know what else needs to be done to merge the PR. Good Day

2022-08-15 03:58 UTC, Thomas-George-T approved these changes

2022-08-15 03:58 UTC, merged

2022-08-15 04:03 UTC, Thomas-George-T commented
Hi @StackDSA,

I had to revert the changes because some files were deleted. If you can make a new PR that would be great. Thanks!